dependencies:
  - name: prometheus-operator
    version: "8.15.5"
    repository: "@stable"
  - name: thanos
    version: "0.3.23"
    repository: "@banzaicloud"
    condition: objectStore.supported
  - name: grafana
    version: "5.8.16"
    repository: "@grafana"
