cloudProvider:
  type: aws
  region: us-east-1

platform:
  authUrl: https://dev.neu.ro
  configUrl: https://dev.neu.ro
  apiUrl: https://dev.neu.ro/api/v1
  accessTokenCookieName: dat
  clusterName: default
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: cluster_token

metricsServer:
  podMetadata:
    annotations:
      iam.amazonaws.com/role: arn:aws:iam::771188043543:role/pricing-d04bce531282b98cb801932de6c118c7

prometheusProxy:
  replicas: 2

grafanaProxy:
  replicas: 2
  ingress:
    extraAnnotations:
      external-dns.platform.neuromation.io: "true"
    hosts: [metrics-dev.neu.ro]

prometheus-operator:
  prometheus:
    prometheusSpec:
      thanos:
        version: v0.13.0
        objectStorageConfig:
          name: thanos-object-storage-config
          key: thanos-object-storage.yaml
      podMetadata:
        annotations:
          iam.amazonaws.com/role: arn:aws:iam::771188043543:role/s3-d04bce531282b98cb801932de6c118c7
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp2

  prometheusOperator:
    kubeletService:
      namespace: platform

  kubelet:
    namespace: platform

thanos:
  store:
    persistentVolumeClaim:
      spec:
        storageClassName: gp2
    annotations:
      iam.amazonaws.com/role: arn:aws:iam::771188043543:role/s3-d04bce531282b98cb801932de6c118c7

  bucket:
    annotations:
      iam.amazonaws.com/role: arn:aws:iam::771188043543:role/s3-d04bce531282b98cb801932de6c118c7

  compact:
    persistentVolumeClaim:
      spec:
        storageClassName: gp2
    annotations:
      iam.amazonaws.com/role: arn:aws:iam::771188043543:role/s3-d04bce531282b98cb801932de6c118c7

  objstore:
    type: S3
    config:
      bucket: neuro-dev-metrics
      endpoint: s3.us-east-1.amazonaws.com

grafana:
  adminPassword: password
