apiVersion: v1
kind: Service
metadata:
  name: grafana-proxy
  labels: {{ include "platform-reports.labels.standard" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: {{ include "platform-reports.name" . }}
    release: {{ .Release.Name | quote }}
    component: grafana-proxy
