apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-proxy
  labels: {{ include "platform-reports.labels.standard" . | nindent 4 }}
    component: grafana-proxy
spec:
  replicas: {{ .Values.grafanaProxy.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ include "platform-reports.name" . }}
      release: {{ .Release.Name | quote }}
      component: grafana-proxy
  template:
    metadata:
      labels:
        app: {{ include "platform-reports.name" . }}
        release: {{ .Release.Name | quote }}
        component: grafana-proxy
      {{- if .Values.secrets }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      {{- end }}
    spec:
      {{- if .Values.image.pullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName | quote }}
      {{- end }}
      containers:
        - name: proxy
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["grafana-proxy"]
          env:
            - name: NP_LOG_LEVEL
              value: {{ .Values.logLevel }}
            - name: NP_CLUSTER_NAME
              value: {{ .Values.platform.clusterName }}
            - name: NP_GRAFANA_HOST
              value: grafana
            - name: NP_GRAFANA_PORT
              value: "80"
            - name: NP_AUTH_URL
              value: {{ .Values.platform.authUrl }}
            - name: NP_AUTH_TOKEN
{{- if .Values.platform.token }}
{{ toYaml .Values.platform.token | indent 14 }}
{{- end }}
            - name: NP_AUTH_ACCESS_TOKEN_COOKIE_NAMES
              value: {{ .Values.platform.accessTokenCookieNames }}
            - name: NP_API_URL
              value: {{ .Values.platform.apiUrl }}
          {{- if .Values.grafanaProxy.resources }}
          resources: {{ toYaml .Values.grafanaProxy.resources | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 3
            periodSeconds: 3
