apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-prometheus-proxy
  labels: {{ include "platform-reports.labels.standard" . | nindent 4 }}
    service: platform-prometheus-proxy
spec:
  replicas: {{ .Values.prometheusProxy.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ include "platform-reports.name" . }}
      release: {{ .Release.Name | quote }}
      service: platform-prometheus-proxy
  template:
    metadata:
      labels:
        app: {{ include "platform-reports.name" . }}
        release: {{ .Release.Name | quote }}
        service: platform-prometheus-proxy
      {{- if .Values.secrets }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      {{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: proxy
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["prometheus-proxy"]
          env:
            - name: NP_LOG_LEVEL
              value: {{ .Values.logLevel }}
            - name: NP_CLUSTER_NAME
              value: {{ .Values.platform.clusterName | quote }}
            - name: NP_PROMETHEUS_HOST
              value: {{ .Values.prometheusProxy.prometheus.host | quote }}
            - name: NP_PROMETHEUS_PORT
              value: {{ .Values.prometheusProxy.prometheus.port | quote }}
            - name: NP_AUTH_URL
              value: {{ .Values.platform.authUrl }}
            - name: NP_AUTH_TOKEN
{{- if .Values.platform.token }}
{{ toYaml .Values.platform.token | indent 14 }}
{{- end }}
            - name: NP_AUTH_ACCESS_TOKEN_COOKIE_NAMES
              value: {{ .Values.platform.accessTokenCookieNames }}
            - name: NP_API_URL
              value: {{ .Values.platform.apiUrl }}
            {{- if .Values.zipkin }}
            - name: NP_ZIPKIN_URL
              value: {{ .Values.zipkin.url }}
            - name: NP_ZIPKIN_SAMPLE_RATE
              value: {{ .Values.zipkin.sampleRate | quote }}
            {{- end }}
            {{- if .Values.sentry }}
            - name: NP_SENTRY_DSN
              value: {{ .Values.sentry.dsn }}
            - name: NP_SENTRY_CLUSTER_NAME
              value: {{ .Values.sentry.clusterName }}
            - name: NP_SENTRY_SAMPLE_RATE
              value: {{ .Values.sentry.sampleRate | quote }}
            {{- end }}
          {{- if .Values.prometheusProxy.resources }}
          resources: {{ toYaml .Values.prometheusProxy.resources | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /api/v1/ping
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/ping
              port: http
            initialDelaySeconds: 3
            periodSeconds: 3
