{{- $prometheusOperatorValues := index .Values "prometheus-operator" -}}
{{- if and $prometheusOperatorValues.prometheusOperator.enabled -}}
{{- if not $prometheusOperatorValues.prometheusOperator.createCustomResource -}}
{{- range $path, $bytes := .Files.Glob "prometheus-crds/*.yaml" }}
{{ $.Files.Get $path }}
---
{{- end }}
{{- end }}
{{- end }}
