{{- if and .Values.prometheusOperator.enabled -}}
{{- if not .Values.prometheus-operator.prometheusOperator.createCustomResource -}}
{{- range $path, $bytes := .Files.Glob "crds/*.yaml" }}
{{ $.Files.Get $path }}
---
{{- end }}
{{- end }}
{{- end }}
