{
 "title": "Credits",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "org_name",
    "label": "Organization",
    "query": "label_values(kube_pod_labels{job=\"kube-state-metrics\",label_platform_neuromation_io_org!=\"no_org\"},label_platform_neuromation_io_org)"
   },
   {
    "name": "user_name",
    "label": "User",
    "query": "label_values(kube_pod_labels{job=\"kube-state-metrics\"},label_platform_neuromation_io_user)"
   }
  ]
 },
 "panels": [
  { "title": "Credits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Jobs",
   "type": "table",
   "description": "Jobs seen in Running state during selected time interval.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "1000 * max by(pod) (max_over_time(kube_pod_running_scheduled_time{job=\"kube-state-metrics\",pod=~\"^job-.+\"}[$__range])) * on(pod) group_left(label_platform_neuromation_io_org,label_platform_neuromation_io_user,label_platform_neuromation_io_preset) kube_pod_labels{job=\"kube-state-metrics\",pod=~\"^job-.+\"}"
    },
    {
     "expr": "(15 / 3600) * sum by(pod) (sum_over_time(kube_pod_credits_per_hour{job=\"neuro-metrics-exporter\",pod=~\"^job-.+\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Users",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "15 / 3600 * sum by(label_platform_neuromation_io_org,label_platform_neuromation_io_user,label_platform_neuromation_io_preset) (sum_over_time(kube_pod_credits_per_hour{job=\"neuro-metrics-exporter\",pod=~\"^job-.+\"}[$__range]) * on(pod) group_left(label_platform_neuromation_io_org,label_platform_neuromation_io_user,label_platform_neuromation_io_preset) kube_pod_labels{job=\"kube-state-metrics\",pod=~\"^job-.+\"}) > 0"
    }
   ]
  },
  {
   "title": "Organizations",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "15 / 3600 * sum by(label_platform_neuromation_io_org,label_platform_neuromation_io_preset) (sum_over_time(kube_pod_credits_per_hour{job=\"neuro-metrics-exporter\",pod=~\"^job-.+\"}[$__range]) * on(pod) group_left(label_platform_neuromation_io_org,label_platform_neuromation_io_preset) kube_pod_labels{job=\"kube-state-metrics\",pod=~\"^job-.+\"}) > 0"
    }
   ]
  },
  {
   "title": "Prices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Pools",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "15 * sum by(label_platform_neuromation_io_nodepool) (sum by(node) (count_over_time(kube_node_price_per_hour{job= \"neuro-metrics-exporter\"}[$__range])) * on(node) group_left(label_platform_neuromation_io_nodepool) kube_node_labels{job= \"kube-state-metrics\",label_platform_neuromation_io_job=\"true\"})"
      },
      {
       "expr": "(15 / 3600) * sum by(label_platform_neuromation_io_nodepool) (sum by(node) (sum_over_time(kube_node_price_per_hour{job= \"neuro-metrics-exporter\"}[$__range])) * on(node) group_left(label_platform_neuromation_io_nodepool) kube_node_labels{job= \"kube-state-metrics\",label_platform_neuromation_io_job=\"true\"})"
      }
     ]
    },
    {
     "title": "Node Pools by User",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "label_join(15 * sum by(label_platform_neuromation_io_user,label_platform_neuromation_io_nodepool) (count_over_time(kube_pod_credits_per_hour_labeled{job=\"neuro-metrics-exporter\",pod=~\"^job-.+\"}[$__range])),\"key\",\",\",\"label_platform_neuromation_io_user\",\"label_platform_neuromation_io_nodepool\")"
      },
      {
       "expr": "max without (label_platform_neuromation_io_user,label_platform_neuromation_io_nodepool) (label_join((15 / 3600) * sum by(label_platform_neuromation_io_user,label_platform_neuromation_io_nodepool) (sum_over_time(kube_pod_credits_per_hour_labeled{job=\"neuro-metrics-exporter\",pod=~\"^job-.+\"}[$__range])),\"key\",\",\",\"label_platform_neuromation_io_user\",\"label_platform_neuromation_io_nodepool\"))"
      }
     ]
    }
   ]
  }
 ]
}