USER-SUPPLIED VALUES:
image:
  repository: "ghcr.io/neuro-inc/platform-reports"
  tag: "23.6.0"
cloudProvider:
  region: us-central1
  serviceAccountSecret:
    key: key_json
    name: gcp-key
  type: gcp
grafana:
  adminPassword: password
  priorityClassName: ""
grafanaProxy:
  fullnameOverride: platform-grafana-proxy
  ingress:
    annotations:
      external-dns.platform.neuromation.io: "true"
      traefik.ingress.kubernetes.io/router.middlewares: platform-platform-ingress-auth@kubernetescrd
      traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
    enabled: true
    hosts:
      - metrics-dev.neu.ro
    ingressClassName: traefik
  nameOverride: platform-grafana-proxy
  replicas: 2
kube-prometheus-stack:
  kubelet:
    namespace: platform
  prometheus:
    prometheusSpec:
      externalLabels:
        cluster: ""
      priorityClassName: ""
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: standard-rwo
      thanos:
        objectStorageConfig:
          key: object-store.yaml
          name: thanos
  prometheusOperator:
    kubeletService:
      namespace: platform
    priorityClassName: ""
metricsExporter:
  fullnameOverride: platform-metrics-exporter
  nameOverride: platform-metrics-exporter
platform:
  accessTokenCookieName: dat
  apiUrl: https://dev.neu.ro/api/v1
  authUrl: https://dev.neu.ro
  clusterName: default
  configUrl: https://dev.neu.ro
  token:
    valueFrom:
      secretKeyRef:
        key: cluster_token
        name: platformservices-secret
priorityClassName: ""
prometheusProxy:
  fullnameOverride: platform-prometheus-proxy
  nameOverride: platform-prometheus-proxy
  replicas: 2
sentry:
  clusterName: dev
  dsn: https://432bc48cd2444be7afec5efeb1fc03a6@o489136.ingest.sentry.io/5530426
  sampleRate: 0.002
thanos:
  compact:
    persistentVolumeClaim:
      spec:
        storageClassName: standard-rwo
  objstoreSecretOverride: thanos
  priorityClassName: ""
  store:
    persistentVolumeClaim:
      spec:
        storageClassName: standard-rwo
