{
 "title": "Jobs",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "user_name", "label": "User Name" }
  ]
 },
 "panels": [
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Jobs",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{job=\"kubelet\",pod=~\"^job-.+\",container!=\"POD\",image!=\"\"}[$__rate_interval])) / sum by (pod) (container_spec_cpu_quota{job=\"kubelet\",pod=~\"^job-.+\",container!=\"POD\",image!=\"\"} / container_spec_cpu_period{job=\"kubelet\",pod=~\"^job-.+\",container!=\"POD\",image!=\"\"}) * 100 * on(pod) group_left(label_platform_neuromation_io_user) kube_pod_labels{job=\"kube-state-metrics\",label_platform_neuromation_io_user=\"$user_name\"}"
    },
    {
     "expr": "sum by (pod) (container_memory_usage_bytes{job=\"kubelet\",pod=~\"^job-.+\",container!=\"POD\",image!=\"\"}) / sum by (pod) (container_spec_memory_limit_bytes{job=\"kubelet\",pod=~\"^job-.+\",container!=\"POD\",image!=\"\"}) * 100 * on(pod) kube_pod_labels{job=\"kube-state-metrics\",label_platform_neuromation_io_user=\"$user_name\"}"
    },
    {
     "expr": "sum by (pod) (time() - container_start_time_seconds{job=\"kubelet\",pod=~\"^job-.+\",container!=\"POD\",image!=\"\"} * on(pod) kube_pod_labels{job=\"kube-state-metrics\",label_platform_neuromation_io_user=\"$user_name\"})"
    },
    {
     "expr": "sum by (pod) (DCGM_FI_DEV_COUNT{job=\"nvidia-dcgm-exporter\"}) * on(pod) group_left(label_platform_neuromation_io_gpu_model) kube_pod_labels{job=\"kube-state-metrics\",label_platform_neuromation_io_user=\"$user_name\",label_platform_neuromation_io_gpu_model!=\"\"}"
    }
   ]
  },
  {
   "title": "All Jobs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "1000 * max by(pod) (max_over_time(container_start_time_seconds{job=\"kubelet\",pod=~\"^job-.+\",container!=\"POD\",image!=\"\"}[$__range])) * on(pod) max by(pod) (max_over_time(kube_pod_labels{job=\"kube-state-metrics\",label_platform_neuromation_io_user=\"$user_name\"}[$__range]))"
    },
    {
     "expr": "max by (pod) (max_over_time(timestamp(container_start_time_seconds{job=\"kubelet\",pod=~\"^job-.+\",container!=\"POD\",image!=\"\"})[$__range:10s])) - on(pod) max by(pod) (max_over_time(container_start_time_seconds{job=\"kubelet\",pod=~\"^job-.+\",container!=\"POD\",image!=\"\"}[$__range])) * on(pod) max by(pod) (max_over_time(kube_pod_labels{job=\"kube-state-metrics\",label_platform_neuromation_io_user=\"$user_name\"}[$__range])) > 0"
    },
    {
     "expr": "sum by (pod) (max_over_time(DCGM_FI_DEV_COUNT{job=\"nvidia-dcgm-exporter\"}[$__range])) * on(pod) group_left(label_platform_neuromation_io_gpu_model) max by(pod,label_platform_neuromation_io_gpu_model) (max_over_time(kube_pod_labels{job=\"kube-state-metrics\",label_platform_neuromation_io_user=\"$user_name\",label_platform_neuromation_io_gpu_model!=\"\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Number of Jobs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count (max by(pod) (max_over_time(kube_pod_status_phase{job=\"kube-state-metrics\",pod=~\"^job-.+\",phase=\"Running\"}[$__rate_interval]) == 1) * on(pod) max by(pod) (max_over_time(kube_pod_labels{job=\"kube-state-metrics\",label_platform_neuromation_io_user=\"$user_name\"}[$__rate_interval])))",
     "legendFormat": "Amount"
    }
   ]
  },
  {
   "title": "Total Number of Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (max by(pod) (max_over_time(kube_pod_status_phase{job=\"kube-state-metrics\",pod=~\"^job-.+\",phase=\"Running\"}[$__range]) == 1) * on(pod) max by(pod) (max_over_time(kube_pod_labels{job=\"kube-state-metrics\",label_platform_neuromation_io_user=\"$user_name\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Resource Consumption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Consumption",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "none", "label": "Core" }
     ],
     "targets": [
      {
       "expr": "sum by (label_platform_neuromation_io_user) (container_spec_cpu_quota{job=\"kubelet\",pod=~\"^job-.+\",container!=\"POD\",image!=\"\"} / container_spec_cpu_period{job=\"kubelet\",pod=~\"^job-.+\",container!=\"POD\",image!=\"\"} * on(pod) kube_pod_labels{job=\"kube-state-metrics\",label_platform_neuromation_io_user=\"$user_name\"})",
       "legendFormat": "CPU"
      }
     ]
    },
    {
     "title": "Memory Consumption",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (label_platform_neuromation_io_user) (container_spec_memory_limit_bytes{job=\"kubelet\",pod=~\"^job-.+\",container!=\"POD\",image!=\"\"} * on(pod) kube_pod_labels{job=\"kube-state-metrics\",label_platform_neuromation_io_user=\"$user_name\"})",
       "legendFormat": "Memory"
      }
     ]
    },
    {
     "title": "GPU Consumption",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (label_platform_neuromation_io_gpu_model) (DCGM_FI_DEV_COUNT{job=\"nvidia-dcgm-exporter\"} * on(pod) group_left(label_platform_neuromation_io_gpu_model) kube_pod_labels{job=\"kube-state-metrics\",label_platform_neuromation_io_user=\"$user_name\",label_platform_neuromation_io_gpu_model!=\"\"})",
       "legendFormat": "{{label_platform_neuromation_io_gpu_model}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU / Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{job=\"kubelet\",pod=~\"^job-.+\",container!=\"POD\",image!=\"\"}[$__rate_interval])) / sum by (pod) (container_spec_cpu_quota{job=\"kubelet\",pod=~\"^job-.+\",container!=\"POD\",image!=\"\"} / container_spec_cpu_period{job=\"kubelet\",pod=~\"^job-.+\",container!=\"POD\",image!=\"\"}) * 100 * on(pod) group_left(label_platform_neuromation_io_user) kube_pod_labels{job=\"kube-state-metrics\",label_platform_neuromation_io_user=\"$user_name\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (container_memory_usage_bytes{job=\"kubelet\",pod=~\"^job-.+\",container!=\"POD\",image!=\"\"}) / sum by (pod) (container_spec_memory_limit_bytes{job=\"kubelet\",pod=~\"^job-.+\",container!=\"POD\",image!=\"\"}) * 100 * on(pod) group_left(label_platform_neuromation_io_user) kube_pod_labels{job=\"kube-state-metrics\",label_platform_neuromation_io_user=\"$user_name\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg by (pod) (DCGM_FI_DEV_GPU_UTIL{job=\"nvidia-dcgm-exporter\"}) * on(pod) kube_pod_labels{job=\"kube-state-metrics\",label_platform_neuromation_io_user=\"$user_name\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GPU Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg by (pod) (DCGM_FI_DEV_MEM_COPY_UTIL{job=\"nvidia-dcgm-exporter\"}) * on(pod) kube_pod_labels{job=\"kube-state-metrics\",label_platform_neuromation_io_user=\"$user_name\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic Received",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (irate(container_network_receive_bytes_total{job=\"kubelet\",pod=~\"^job-.+\"}[$__rate_interval])) * on(pod) kube_pod_labels{job=\"kube-state-metrics\",label_platform_neuromation_io_user=\"$user_name\"} * 8",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Network Traffic Sent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (irate(container_network_transmit_bytes_total{job=\"kubelet\",pod=~\"^job-.+\"}[$__rate_interval])) * on(pod) group_left(label_platform_neuromation_io_user) kube_pod_labels{job=\"kube-state-metrics\",label_platform_neuromation_io_user=\"$user_name\"} * 8",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "File System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "File System Data Read",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (irate(container_fs_reads_bytes_total{job=\"kubelet\",pod=~\"^job-.+\"}[$__rate_interval])) * on(pod) group_left(label_platform_neuromation_io_user) kube_pod_labels{job=\"kube-state-metrics\",label_platform_neuromation_io_user=\"$user_name\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "File System Data Written",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (irate(container_fs_writes_bytes_total{job=\"kubelet\"}[$__rate_interval])) * on(pod) group_left(label_platform_neuromation_io_user) topk by(pod) (1, kube_pod_labels{job=\"kube-state-metrics\",label_platform_neuromation_io_user=\"$user_name\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}