{
 "title": "App",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "app_instance_name", "label": "App name" },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "query_result(kube_pod_container_info{job=\"kube-state-metrics\"} * on (pod) group_left(label_platform_apolo_us_app_instance_name) kube_pod_labels{job=\"kube-state-metrics\", label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "App Instance Name",
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center; font-weight: bold\">${app_instance_name}</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Preset",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(label_platform_apolo_us_preset) (kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"})",
     "legendFormat": "{{label_platform_neuromation_io_project}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{job=\"kubelet\",container=~\"^$container$\",image!=\"\"}[$__rate_interval]) * on (pod) group_left (label_platform_apolo_us_app_instance_name) kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\",container=~\"^$container$\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\",container=~\"^$container$\",image!=\"\"} * on (pod) group_left (label_platform_apolo_us_app_instance_name) kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"memory\",container=~\"^$container$\"}) * 100\n"
    }
   ]
  },
  {
   "title": "GPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{job=\"nvidia-dcgm-exporter\"} * on (pod) group_left (label_platform_apolo_us_app_instance_name) kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"})\n"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{job=\"nvidia-dcgm-exporter\"} * on (pod) group_left (label_platform_apolo_us_app_instance_name) kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"}) / sum(DCGM_FI_DEV_FB_USED{job=\"nvidia-dcgm-exporter\"} * on (pod) group_left (label_platform_apolo_us_app_instance_name) kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"} + DCGM_FI_DEV_FB_FREE{job=\"nvidia-dcgm-exporter\"} * on (pod) group_left (label_platform_apolo_us_app_instance_name) kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"})"
    }
   ]
  },
  {
   "title": "Project",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(label_platform_apolo_us_project) (kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"})",
     "legendFormat": "{{label_platform_neuromation_io_project}}"
    }
   ]
  },
  {
   "title": "Organization",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(label_platform_apolo_us_org) (kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"})",
     "legendFormat": "{{label_platform_neuromation_io_org}}"
    }
   ]
  },
  {
   "title": "CPU / Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "Core" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{job=\"kubelet\",container=~\"^$container$\",image!=\"\"}[$__rate_interval]) * on (pod) group_left (label_platform_apolo_us_app_instance_name) kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"}) ",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\",container=~\"^$container$\"} * on (pod) group_left (label_platform_apolo_us_app_instance_name) kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"}) - sum(irate(container_cpu_usage_seconds_total{job=\"kubelet\",container=~\"^$container$\",image!=\"\"}[$__rate_interval]) * on (pod) group_left (label_platform_apolo_us_app_instance_name) kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\",container=~\"^$container$\",image!=\"\"} * on (pod) group_left (label_platform_apolo_us_app_instance_name) kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"}) ",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"memory\"} * on (pod) group_left (label_platform_apolo_us_app_instance_name) kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"}) - sum(container_memory_working_set_bytes{job=\"kubelet\",container=~\"^$container$\",image!=\"\"} * on (pod) group_left (label_platform_apolo_us_app_instance_name) kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "GPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{job=\"nvidia-dcgm-exporter\"} * on (pod) group_left (label_platform_apolo_us_app_instance_name) kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{job=\"nvidia-dcgm-exporter\"} * on (pod) group_left (label_platform_apolo_us_app_instance_name) kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"}",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "max (DCGM_FI_DEV_FB_USED{job=\"nvidia-dcgm-exporter\"} * on (pod) group_left (label_platform_apolo_us_app_instance_name) kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"} + DCGM_FI_DEV_FB_FREE{job=\"nvidia-dcgm-exporter\"} * on (pod) group_left (label_platform_apolo_us_app_instance_name) kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Receive Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\"}[$__rate_interval]) * on (pod) group_left (label_platform_apolo_us_app_instance_name) kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"}) * 8",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Network Send Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{job=\"kubelet\"}[$__rate_interval]) * on (pod) group_left (label_platform_apolo_us_app_instance_name) kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"}) * 8",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "File System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "File System Read Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{job=\"kubelet\",container=~\"^$container$\"}[$__rate_interval]) * on (pod) group_left (label_platform_apolo_us_app_instance_name) kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"})",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "File System Write Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{job=\"kubelet\",container=~\"^$container$\"}[$__rate_interval]) * on (pod) group_left (label_platform_apolo_us_app_instance_name) kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=\"${app_instance_name}\"})",
     "legendFormat": "Rate"
    }
   ]
  }
 ]
}