{
 "title": "Apps",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "org_name",
    "label": "Organization",
    "query": "label_values(kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_org!=\"no_org\"},label_platform_apolo_us_org)"
   },
   {
    "name": "project_name",
    "label": "Project",
    "query": "label_values(kube_pod_labels{job=\"kube-state-metrics\"},label_platform_apolo_us_project)"
   },
   {
    "name": "user_name",
    "label": "User",
    "query": "label_values(kube_pod_labels{job=\"kube-state-metrics\"},label_platform_apolo_us_user)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": " ",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (label_platform_apolo_us_org,label_platform_apolo_us_project, label_platform_apolo_us_user, label_platform_apolo_us_preset, label_platform_apolo_us_app_instance_name) (\n        sum by (pod) (\n          irate(container_cpu_usage_seconds_total{container!=\"POD\",image!=\"\",job=\"kubelet\"}[$__rate_interval])\n        )\n      /\n        sum by (pod) (\n          kube_pod_container_resource_requests{container!=\"POD\",job=\"kube-state-metrics\",resource=\"cpu\"}\n        )\n    *\n      100\n  * on (pod) group_left (label_platform_apolo_us_org,label_platform_apolo_us_project, label_platform_apolo_us_user, label_platform_apolo_us_preset, label_platform_apolo_us_app_instance_name)\n    kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=~\".+\",label_platform_apolo_us_org=~\"^$org_name$\",label_platform_apolo_us_project=~\"^$project_name$\",label_platform_apolo_us_user=~\"^$user_name$\"}\n)"
    },
    {
     "expr": "sum by (label_platform_apolo_us_org,label_platform_apolo_us_project, label_platform_apolo_us_user, label_platform_apolo_us_preset, label_platform_apolo_us_app_instance_name) (\n        sum by (pod) (container_memory_working_set_bytes{container!=\"POD\",image!=\"\",job=\"kubelet\"})\n      /\n        sum by (pod) (\n          kube_pod_container_resource_limits{container!=\"POD\",job=\"kube-state-metrics\",resource=\"memory\"}\n        )\n    *\n      100\n  * on (pod) group_left (label_platform_apolo_us_org,label_platform_apolo_us_project, label_platform_apolo_us_user, label_platform_apolo_us_preset, label_platform_apolo_us_app_instance_name)\n    kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=~\".+\",label_platform_apolo_us_org=~\"^$org_name$\",label_platform_apolo_us_project=~\"^$project_name$\",label_platform_apolo_us_user=~\"^$user_name$\"}\n)"
    }
   ]
  },
  {
   "title": "CPU / Memory / GPU Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none", "label": "Core" }
   ],
   "targets": [
    {
     "expr": "sum (\n    kube_pod_container_resource_requests{container!=\"POD\",job=\"kube-state-metrics\",resource=\"cpu\"}\n  * on (pod) group_left(label_platform_apolo_us_app_instance_name)\n    kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=~\".+\",label_platform_apolo_us_org=~\"^$org_name$\",label_platform_apolo_us_project=~\"^$project_name$\",label_platform_apolo_us_user=~\"^$user_name$\"}\n)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n    sum by (pod) (\n      kube_pod_container_resource_limits{container!=\"POD\",job=\"kube-state-metrics\",resource=\"memory\"}\n    )\n  * on (pod)\n    kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=~\".+\",label_platform_apolo_us_org=~\"^$org_name$\",label_platform_apolo_us_project=~\"^$project_name$\",label_platform_apolo_us_user=~\"^$user_name$\"}\n)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "GPU by Device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (label_platform_neuromation_io_gpu_model) (\n    max by (pod) (DCGM_FI_DEV_COUNT{job=\"nvidia-dcgm-exporter\"})\n  * on (pod) group_left (label_platform_neuromation_io_gpu_model)\n    kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=~\".+\",label_platform_apolo_us_org=~\"^$org_name$\",label_platform_apolo_us_project=~\"^$project_name$\",label_platform_apolo_us_user=~\"^$user_name$\",label_platform_neuromation_io_gpu_model!=\"\"}\n)",
     "legendFormat": "{{label_platform_neuromation_io_gpu_model}}"
    }
   ]
  },
  {
   "title": "CPU / Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (label_platform_apolo_us_app_instance_name) (\n        sum by (pod) (\n          irate(container_cpu_usage_seconds_total{container!=\"POD\",image!=\"\",job=\"kubelet\"}[5m])\n        )\n      /\n        sum by (pod) (\n          kube_pod_container_resource_requests{container!=\"POD\",job=\"kube-state-metrics\",resource=\"cpu\"}\n        )\n    *\n      100\n  * on (pod) group_left (label_platform_apolo_us_app_instance_name)\n    kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=~\".+\",label_platform_apolo_us_org=~\"^$org_name$\",label_platform_apolo_us_project=~\"^$project_name$\",label_platform_apolo_us_user=~\"^$user_name$\"}\n)",
     "legendFormat": "{{label_platform_apolo_us_app_instance_name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (label_platform_apolo_us_app_instance_name) (\n        sum by (pod) (container_memory_working_set_bytes{container!=\"POD\",image!=\"\",job=\"kubelet\"})\n      /\n        sum by (pod) (\n          kube_pod_container_resource_limits{container!=\"POD\",job=\"kube-state-metrics\",resource=\"memory\"}\n        )\n    *\n      100\n  * on (pod) group_left (label_platform_apolo_us_app_instance_name)\n    kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=~\".+\",label_platform_apolo_us_org=~\"^$org_name$\",label_platform_apolo_us_project=~\"^$project_name$\",label_platform_apolo_us_user=~\"^$user_name$\"}\n)",
     "legendFormat": "{{label_platform_apolo_us_app_instance_name}}"
    }
   ]
  },
  {
   "title": "GPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (label_platform_apolo_us_app_instance_name) (\n    avg by (pod) (DCGM_FI_DEV_GPU_UTIL{job=\"nvidia-dcgm-exporter\"})\n  * on (pod) group_left (label_platform_apolo_us_app_instance_name)\n    kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=~\".+\",label_platform_apolo_us_org=\"$org_name\",label_platform_apolo_us_project=~\"^$project_name$\",label_platform_apolo_us_user=~\"^$user_name$\"}\n)",
     "legendFormat": "{{label_platform_apolo_us_app_instance_name}}"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (label_platform_apolo_us_app_instance_name) (\n      sum by (pod) (DCGM_FI_DEV_FB_USED{job=\"nvidia-dcgm-exporter\"})\n    /\n      sum by (pod) (\n        DCGM_FI_DEV_FB_USED{job=\"nvidia-dcgm-exporter\"} + DCGM_FI_DEV_FB_FREE{job=\"nvidia-dcgm-exporter\"}\n      )\n  * on (pod) group_left (label_platform_apolo_us_app_instance_name)\n    kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=~\".+\",label_platform_apolo_us_org=\"$org_name\",label_platform_apolo_us_project=~\"^$project_name$\",label_platform_apolo_us_user=~\"^$user_name$\"}\n)",
     "legendFormat": "{{label_platform_apolo_us_app_instance_name}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Traffic Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (label_platform_apolo_us_app_instance_name) (\n      sum by (pod) (irate(container_network_receive_bytes_total{job=\"kubelet\"}[$__rate_interval]))\n    * on (pod) group_left (label_platform_apolo_us_app_instance_name)\n      kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=~\".+\",label_platform_apolo_us_org=~\"^$org_name$\",label_platform_apolo_us_project=~\"^$project_name$\",label_platform_apolo_us_user=~\"^$user_name$\"}\n  *\n    8\n)",
     "legendFormat": "{{label_platform_apolo_us_app_instance_name}}"
    }
   ]
  },
  {
   "title": "Network Traffic Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (label_platform_apolo_us_app_instance_name) (\n      sum by (pod) (irate(container_network_transmit_bytes_total{job=\"kubelet\"}[$__rate_interval]))\n    * on (pod) group_left (label_platform_apolo_us_app_instance_name)\n      kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=~\".+\",label_platform_apolo_us_org=~\"^$org_name$\",label_platform_apolo_us_project=~\"^$project_name$\",label_platform_apolo_us_user=~\"^$user_name$\"}\n  *\n    8\n)",
     "legendFormat": "{{label_platform_apolo_us_app_instance_name}}"
    }
   ]
  },
  {
   "title": "File System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "File System Data Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (label_platform_apolo_us_app_instance_name) (\n    sum by (pod) (irate(container_fs_reads_bytes_total{job=\"kubelet\"}[$__rate_interval]))\n  * on (pod) group_left (label_platform_apolo_us_app_instance_name)\n    kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=~\".+\",label_platform_apolo_us_org=~\"^$org_name$\",label_platform_apolo_us_project=~\"^$project_name$\",label_platform_apolo_us_user=~\"^$user_name$\"}\n)",
     "legendFormat": "{{label_platform_apolo_us_app_instance_name}}"
    }
   ]
  },
  {
   "title": "File System Data Written",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (label_platform_apolo_us_app_instance_name) (\n    sum by (pod) (irate(container_fs_writes_bytes_total{job=\"kubelet\"}[$__rate_interval]))\n  * on (pod) group_left (label_platform_apolo_us_app_instance_name)\n    kube_pod_labels{job=\"kube-state-metrics\",label_platform_apolo_us_app_instance_name=~\".+\",label_platform_apolo_us_org=~\"^$org_name$\",label_platform_apolo_us_project=~\"^$project_name$\",label_platform_apolo_us_user=~\"^$user_name$\"}\n)",
     "legendFormat": "{{label_platform_apolo_us_app_instance_name}}"
    }
   ]
  }
 ]
}