{
 "title": "Cluster resources",
 "description": "Cluster resource usage reports per organization",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "org_name",
    "label": "Organization",
    "query": {
     "query": "label_values(kube_pod_labels{job=\"kube-state-metrics\", label_platform_apolo_us_org!=\"no_org\"},label_platform_apolo_us_org)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource presets allocation",
   "type": "timeseries",
   "description": "Represents the amount of workloads running on each resource preset for each organization. ",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (label_platform_apolo_us_org, label_platform_apolo_us_preset) (\n  kube_pod_labels{label_platform_apolo_us_org=~\"${org_name}\", label_platform_apolo_us_preset!=\"\", job=\"kube-state-metrics\"}\n    * on(pod, uid) group_left()\n      max by (pod, uid) (\n       (kube_pod_status_phase{phase=\"Running\", job=\"kube-state-metrics\"} == 1)\n    )\n)",
     "legendFormat": "{{label_platform_apolo_us_org}} - {{label_platform_apolo_us_preset}}"
    }
   ]
  },
  {
   "title": "Hardware allocation details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "vCPU allocation",
     "type": "timeseries",
     "description": "Represents the amount of vCPUs occupied by each org.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (label_platform_apolo_us_org) (\n  kube_pod_container_resource_requests{resource=\"cpu\", job=\"kube-state-metrics\"} \n  * on(namespace, pod, uid) group_left(label_platform_apolo_us_org)\n    max by (namespace, pod, uid, label_platform_apolo_us_org) (\n      kube_pod_labels{label_platform_apolo_us_org!=\"\", label_platform_apolo_us_org=~\"${org_name}\", job=\"kube-state-metrics\"}\n    )\n  * on(namespace, pod, uid) group_left()\n    max by (namespace, pod, uid) (\n      (kube_pod_status_phase{phase=~\"Running\", job=\"kube-state-metrics\"} == 1)\n    )\n)",
       "legendFormat": "{{label_platform_apolo_us_org}}"
      }
     ]
    },
    {
     "title": "RAM allocation",
     "type": "timeseries",
     "description": "Represent the amount of RAM used by each organization (IEC units).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (label_platform_apolo_us_org) (\n  kube_pod_container_resource_requests{resource=\"memory\", job=\"kube-state-metrics\"} \n  * on(namespace, pod, uid) group_left(label_platform_apolo_us_org)\n    max by (namespace, pod, uid, label_platform_apolo_us_org) (\n      kube_pod_labels{label_platform_apolo_us_org!=\"\", label_platform_apolo_us_org=~\"${org_name}\", job=\"kube-state-metrics\"}\n    )\n  * on(namespace, pod, uid) group_left()\n      max by (namespace, pod, uid) (\n      (kube_pod_status_phase{phase=~\"Running\", job=\"kube-state-metrics\"} == 1)\n    )\n)",
       "legendFormat": "{{label_platform_apolo_us_org}}"
      }
     ]
    },
    {
     "title": "Accelerator allocation",
     "type": "timeseries",
     "description": "Represent the amount of accelerator (GPU) models allocated by each org.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (label_platform_apolo_us_org, label_platform_neuromation_io_accelerator) (\n  kube_pod_container_resource_requests{resource=~\".*gpu.*\", job=\"kube-state-metrics\"}\n  * on(namespace, pod) group_left(label_platform_apolo_us_org)\n    max by (namespace, pod, label_platform_apolo_us_org) (\n      kube_pod_labels{label_platform_apolo_us_org!=\"\", label_platform_apolo_us_org=~\"${org_name}\", job=\"kube-state-metrics\"}\n    )\n  * on(pod) group_left()\n    max by (pod) (\n      kube_pod_status_phase{phase=\"Running\", job=\"kube-state-metrics\"} == 1\n    )\n  * on(node) group_left(label_platform_neuromation_io_accelerator)\n    max by (node, label_platform_neuromation_io_accelerator) (\n      kube_node_labels{label_platform_neuromation_io_accelerator!=\"\", job=\"kube-state-metrics\"}\n    )\n)",
       "legendFormat": "{{label_platform_apolo_us_org}} - {{label_platform_neuromation_io_accelerator}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage allocation",
     "type": "timeseries",
     "description": "The amount of storage used by each organization (SI units).",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (org_name) (\n avg by (org_name, project_name) (storage_used_bytes{org_name=~\"${org_name}\", job=\"platform-storage-metrics\"})\n)",
       "legendFormat": "{{org_name}}"
      }
     ]
    }
   ]
  }
 ]
}