{
 "title": "Services",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "kube_pod_labels{job='kube-state-metrics',label_service!=''}"
   }
  ]
 },
 "panels": [
  { "title": "CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "Core" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (irate(container_cpu_usage_seconds_total{job=\"kubelet\",container!=\"POD\",image!=\"\"}[$__rate_interval])) * on(pod) kube_pod_labels{job=\"kube-state-metrics\",label_service=\"$service\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(sum by(pod) (kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\",container!=\"POD\"}) * on(pod) kube_pod_labels{job=\"kube-state-metrics\",label_service=\"$service\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{job=\"kubelet\",container!=\"POD\",image!=\"\"}) * on(pod) kube_pod_labels{job=\"kube-state-metrics\",label_service=\"$service\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(sum by(pod) (kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"memory\",container!=\"POD\"}) * on(pod) kube_pod_labels{job=\"kube-state-metrics\",label_service=\"$service\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Network Receive Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (irate(container_network_receive_bytes_total{job=\"kubelet\"}[$__rate_interval]))  * on(pod) kube_pod_labels{job=\"kube-state-metrics\",label_service=\"$service\"} * 8",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Send Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (irate(container_network_transmit_bytes_total{job=\"kubelet\"}[$__rate_interval])) * on(pod) kube_pod_labels{job=\"kube-state-metrics\",label_service=\"$service\"} * 8",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "File System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "File System Read Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (irate(container_fs_reads_bytes_total{job=\"kubelet\"}[$__rate_interval]))  * on(pod) kube_pod_labels{job=\"kube-state-metrics\",label_service=\"$service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "File System Write Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (irate(container_fs_writes_bytes_total{job=\"kubelet\"}[$__rate_interval])) * on(pod) kube_pod_labels{job=\"kube-state-metrics\",label_service=\"$service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}