{
 "title": "Prices",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Jobs Credits",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(15 / 3600) * sum (sum_over_time(kube_pod_credits_per_hour{job=\"neuro-metrics-exporter\",pod=~\"^job-.+\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Jobs Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "15 * sum (count_over_time(kube_pod_credits_per_hour_labeled{job=\"neuro-metrics-exporter\",pod=~\"^job-.+\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Nodes Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(15 / 3600) * sum (sum by(node) (sum_over_time(kube_node_price_per_hour{job= \"neuro-metrics-exporter\"}[$__range])) * on(node) group_left(label_platform_neuromation_io_nodepool) max by(node,label_platform_neuromation_io_nodepool) (max_over_time(kube_node_labels{job= \"kube-state-metrics\",label_platform_neuromation_io_nodepool!= \"platform\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Nodes Up Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "15 * sum (count_over_time(kube_node_price_per_hour{job= \"neuro-metrics-exporter\"}[$__range]) * on(node) group_left(label_platform_neuromation_io_nodepool) max by(node,label_platform_neuromation_io_nodepool) (max_over_time(kube_node_labels{job= \"kube-state-metrics\",label_platform_neuromation_io_nodepool!= \"platform\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "table",
   "description": "Jobs seen in Running state during selected time interval.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "1000 * max by(pod) (max_over_time(kube_pod_running_scheduled_time{job=\"kube-state-metrics\",pod=~\"^job-.+\"}[$__range])) * on(pod) group_left(label_platform_neuromation_io_user,label_platform_neuromation_io_preset) max by(pod,label_platform_neuromation_io_user,label_platform_neuromation_io_preset) (max_over_time(kube_pod_labels{job=\"kube-state-metrics\",pod=~\"^job-.+\"}[$__range]))"
    },
    {
     "expr": "(15 / 3600) * sum by(pod) (sum_over_time(kube_pod_credits_per_hour{job=\"neuro-metrics-exporter\",pod=~\"^job-.+\"}[$__range]))"
    }
   ]
  },
  {
   "title": "User Node Pools",
   "type": "table",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "label_join(15 * sum by(label_platform_neuromation_io_user,label_platform_neuromation_io_nodepool) (count_over_time(kube_pod_credits_per_hour_labeled{job=\"neuro-metrics-exporter\",pod=~\"^job-.+\"}[$__range])),\"key\",\",\",\"label_platform_neuromation_io_user\",\"label_platform_neuromation_io_nodepool\")"
    },
    {
     "expr": "max without (label_platform_neuromation_io_user,label_platform_neuromation_io_nodepool) (label_join((15 / 3600) * sum by(label_platform_neuromation_io_user,label_platform_neuromation_io_nodepool) (sum_over_time(kube_pod_credits_per_hour_labeled{job=\"neuro-metrics-exporter\",pod=~\"^job-.+\"}[$__range])),\"key\",\",\",\"label_platform_neuromation_io_user\",\"label_platform_neuromation_io_nodepool\"))"
    }
   ]
  },
  {
   "title": "Users",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 12 },
   "targets": [
    {
     "expr": "15 * sum by(label_platform_neuromation_io_user) (count_over_time(kube_pod_credits_per_hour_labeled{job=\"neuro-metrics-exporter\",pod=~\"^job-.+\"}[$__range]))"
    },
    {
     "expr": "(15 / 3600) * sum by(label_platform_neuromation_io_user) (sum_over_time(kube_pod_credits_per_hour_labeled{job=\"neuro-metrics-exporter\",pod=~\"^job-.+\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Node Pools",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 19 },
   "targets": [
    {
     "expr": "15 * sum by(label_platform_neuromation_io_nodepool) (sum by(node) (count_over_time(kube_node_price_per_hour{job= \"neuro-metrics-exporter\"}[$__range])) * on(node) group_left(label_platform_neuromation_io_nodepool) max by(node,label_platform_neuromation_io_nodepool) (max_over_time(kube_node_labels{job= \"kube-state-metrics\",label_platform_neuromation_io_nodepool!= \"platform\"}[$__range])))"
    },
    {
     "expr": "(15 / 3600) * sum by(label_platform_neuromation_io_nodepool) (sum by(node) (sum_over_time(kube_node_price_per_hour{job= \"neuro-metrics-exporter\"}[$__range])) * on(node) group_left(label_platform_neuromation_io_nodepool) max by(node,label_platform_neuromation_io_nodepool) (max_over_time(kube_node_labels{job= \"kube-state-metrics\",label_platform_neuromation_io_nodepool!= \"platform\"}[$__range])))"
    }
   ]
  }
 ]
}