apiVersion: v1
kind: Service
metadata:
  name: {{ include "platformReports.metricsExporter.fullname" . }}
  labels: {{ include "platformReports.labels.standard" . | nindent 4 }}
    service: platform-metrics-exporter
spec:
  selector:
    app: {{ include "platformReports.name" . }}
    release: {{ .Release.Name | quote }}
    service: platform-metrics-exporter
  ports:
    - name: metrics
      port: {{ .Values.metricsExporter.port }}
      targetPort: metrics
