apiVersion: v1
kind: Service
metadata:
  name: {{ include "platformReports.metricsApi.fullname" . }}
  labels: {{ include "platformReports.labels.standard" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: {{ include "platformReports.name" . }}
    release: {{ .Release.Name | quote }}
    service: platform-metrics-api
