{{- if .Values.nvidiaDCGMExporter.enabled }}
{{- if hasKey .Values.nvidiaDCGMExporter.service.ports.metrics "name" }}
{{- fail "Cannot override nvidia-dcgm-exporter metrics port name" }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platformReports.nvidiaDCGMExporter.fullname" . }}
  labels: {{ include "platformReports.labels.standard" . | nindent 4 }}
    service: nvidia-dcgm-exporter
spec:
  selector: {{ toYaml .Values.nvidiaDCGMExporter.service.selector | nindent 4 }}
  ports:
    - name: metrics
{{ toYaml .Values.nvidiaDCGMExporter.service.ports.metrics | indent 6 }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "platformReports.nvidiaDCGMExporter.fullname" . }}
  labels: {{ include "platformReports.labels.standard" . | nindent 4 }}
    service: nvidia-dcgm-exporter
spec:
  selector:
    matchLabels:
      app: {{ include "platformReports.name" . }}
      release: {{ .Release.Name | quote }}
      service: nvidia-dcgm-exporter
  endpoints:
    - port: metrics
      path: /metrics
      honorLabels: true
      interval: 15s
      relabelings:
        - sourceLabels:
            - __metrics_path__
          targetLabel: metrics_path
{{- end }}
