apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "platformReports.fullname" . }}-log-streams
  labels:
    {{- $labels := include "platformReports.labels.standard" . | fromYaml -}}
    {{- $_ := set $labels "release" .Values.prometheusRuleSelectorRelease -}}
    {{- toYaml $labels | nindent 4 }}
spec:
{{ .Files.Get "files/prometheus-rules/log-streams.yaml" | indent 2 }}
