{
 "title": "Job",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "job_id", "label": "Job id" }
  ]
 },
 "panels": [
  {
   "title": "Job",
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center; font-weight: bold\">${job_id}</div>"
   }
  },
  {
   "title": "Preset",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_labels{job=\"kube-state-metrics\",pod=\"$job_id\"}",
     "legendFormat": "{{label_platform_neuromation_io_preset}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{job=\"kubelet\",pod=\"$job_id\",container!=\"POD\",image!=\"\"}[$__rate_interval])) / sum(container_spec_cpu_quota{job=\"kubelet\",pod=\"$job_id\",container!=\"POD\",image!=\"\"} / container_spec_cpu_period{job=\"kubelet\",pod=\"$job_id\",container!=\"POD\",image!=\"\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\",pod=\"$job_id\",container!=\"POD\",image!=\"\"}) / sum(container_spec_memory_limit_bytes{job=\"kubelet\",pod=\"$job_id\",container!=\"POD\",image!=\"\"}) * 100"
    }
   ]
  },
  {
   "title": "GPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{job=\"nvidia-dcgm-exporter\",pod=\"$job_id\"})"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{job=\"nvidia-dcgm-exporter\",pod=\"$job_id\"}) / sum(DCGM_FI_DEV_FB_USED{job=\"nvidia-dcgm-exporter\",pod=\"$job_id\"} + DCGM_FI_DEV_FB_FREE{job=\"nvidia-dcgm-exporter\",pod=\"$job_id\"})"
    }
   ]
  },
  {
   "title": "Organization",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_labels{job=\"kube-state-metrics\",pod=\"$job_id\",label_platform_neuromation_io_org!=\"no_org\"}",
     "legendFormat": "{{label_platform_neuromation_io_org}}"
    }
   ]
  },
  {
   "title": "User",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(label_platform_neuromation_io_user) (kube_pod_labels{job=\"kube-state-metrics\",pod=\"$job_id\"})",
     "legendFormat": "{{label_platform_neuromation_io_user}}"
    }
   ]
  },
  { "title": "CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "Core" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{job=\"kubelet\",pod=\"$job_id\",container!=\"POD\",image!=\"\"}[$__rate_interval]))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(container_spec_cpu_quota{job=\"kubelet\",pod=\"$job_id\",container!=\"POD\",image!=\"\"} / container_spec_cpu_period{job=\"kubelet\",pod=\"$job_id\",container!=\"POD\",image!=\"\"}) - sum(irate(container_cpu_usage_seconds_total{job=\"kubelet\",pod=\"$job_id\",container!=\"POD\",image!=\"\"}[$__rate_interval]))",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\",pod=\"$job_id\",container!=\"POD\",image!=\"\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{job=\"kubelet\",pod=\"$job_id\",container!=\"POD\",image!=\"\"}) - sum(container_memory_working_set_bytes{job=\"kubelet\",pod=\"$job_id\",container!=\"POD\",image!=\"\"})",
     "legendFormat": "Free"
    }
   ]
  },
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "GPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{job=\"nvidia-dcgm-exporter\",pod=\"$job_id\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{job=\"nvidia-dcgm-exporter\",pod=\"$job_id\"}",
     "legendFormat": "GPU {{gpu}}"
    },
    {
     "expr": "max (DCGM_FI_DEV_FB_USED{job=\"nvidia-dcgm-exporter\",pod=\"$job_id\"} + DCGM_FI_DEV_FB_FREE{job=\"nvidia-dcgm-exporter\",pod=\"$job_id\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Receive Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\",pod=\"$job_id\"}[$__rate_interval])) * 8",
       "legendFormat": "Rate"
      }
     ]
    },
    {
     "title": "Network Send Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{job=\"kubelet\",pod=\"$job_id\"}[$__rate_interval])) * 8",
       "legendFormat": "Rate"
      }
     ]
    }
   ]
  },
  {
   "title": "File System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "File System Read Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_fs_reads_bytes_total{job=\"kubelet\",pod=\"$job_id\"}[$__rate_interval]))",
       "legendFormat": "Rate"
      }
     ]
    },
    {
     "title": "File System Write Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_fs_writes_bytes_total{job=\"kubelet\",pod=\"$job_id\"}[$__rate_interval]))",
       "legendFormat": "Rate"
      }
     ]
    }
   ]
  }
 ]
}