{
 "title": "Overview",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum(\n  sum by(node) (\n    avg by(node) (\n      1 - irate(node_cpu_seconds_total{mode=\"idle\", job=\"node-exporter\"}[$__rate_interval]) * on(pod) group_left(node) kube_pod_info{job=\"kube-state-metrics\"}\n    )\n    *\n    on(node) (cpu_max_watts{job=\"neuro-metrics-exporter\"} - cpu_min_watts{job= \"neuro-metrics-exporter\"})\n    +\n    on(node) cpu_min_watts{job= \"neuro-metrics-exporter\"}\n  )\n)",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{job=\"nvidia-dcgm-exporter\"} < 100000)",
     "legendFormat": "GPU"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_load15{job=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "Power Last Hour",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    # CPU kW per cluster per step\n    sum(\n        # avg CPU kWh per instance per step\n        (\n            # avg CPU uilization per instance\n            avg by(node) (\n              1 - irate(node_cpu_seconds_total{mode=\"idle\", job=\"node-exporter\"}[$__interval]) * on(pod) group_left(node) kube_pod_info{job=\"kube-state-metrics\"}\n            )\n            # CPU load kW per instance\n            * on(node) ((cpu_max_watts{job=\"neuro-metrics-exporter\"} - cpu_min_watts{job= \"neuro-metrics-exporter\"}) / 1000)\n            # CPU min kW per instance\n            + on(node) (cpu_min_watts{job= \"neuro-metrics-exporter\"} / 1000)\n        )\n        \n    )\n    # GPU kW per cluster per step\n    + sum(avg_over_time((DCGM_FI_DEV_POWER_USAGE{job=\"nvidia-dcgm-exporter\"} < 100000 or on() vector(0))[$__interval:]) / 1000)\n)\n    \n# step in hours\n* ($__interval_ms / 1000 / 60 / 60)"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * avg(avg by(instance) (1 - irate(node_cpu_seconds_total{mode=\"idle\", job=\"node-exporter\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "CO2eq kWh",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "massg" }
   ],
   "targets": [
    {
     "expr": "(\n    # CPU kW per cluster per step\n    sum(\n        # avg CPU kWh per instance per step\n        (\n            # avg CPU uilization per instance\n            avg by(node) (\n              1 - irate(node_cpu_seconds_total{mode=\"idle\", job=\"node-exporter\"}[$__interval]) * on(pod) group_left(node) kube_pod_info{job=\"kube-state-metrics\"}\n            )\n            # CPU load kW per instance\n            * on(node) ((cpu_max_watts{job=\"neuro-metrics-exporter\"} - cpu_min_watts{job= \"neuro-metrics-exporter\"}) / 1000)\n            # CPU min kW per instance\n            + on(node) (cpu_min_watts{job= \"neuro-metrics-exporter\"} / 1000)\n        )\n        \n    )\n    # GPU kW per cluster per step\n    + sum(avg_over_time((DCGM_FI_DEV_POWER_USAGE{job=\"nvidia-dcgm-exporter\"} < 100000 or on() vector(0))[$__interval:]) / 1000)\n)\n    \n# step in hours\n* ($__interval_ms / 1000 / 60 / 60)\n# g CO2eq per kWh\n* 323"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{job=\"nvidia-dcgm-exporter\"} and DCGM_FI_DEV_GPU_UTIL{job=\"nvidia-dcgm-exporter\"} < 100000)"
    }
   ]
  }
 ]
}