apiVersion: v2
name: platform-reports
description: A Helm chart for platform-reports service
version: $CHART_VERSION
appVersion: $APP_VERSION
dependencies:
  - name: kube-prometheus-stack
    version: "10.3.5"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: thanos
    version: "0.3.23"
    repository: "https://kubernetes-charts.banzaicloud.com"
    condition: objectStore.supported
  - name: grafana
    version: "6.2.2"
    repository: "https://grafana.github.io/helm-charts"
  - name: k8s-resources
    version: "1.0.1"
    repository: https://neuro-inc.github.io/helm-charts
