apiVersion: v2
name: platform-reports
description: A Helm chart for platform-reports service
version: 1.0.0
appVersion: 1.0.0
kubeVersion: ">=1.21.0-0"
dependencies:
  - name: kube-prometheus-stack
    version: "54.2.2"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: thanos
    version: "0.3.23"
    repository: "https://kubernetes-charts.banzaicloud.com"
    condition: prometheus.remoteStorageEnabled
  - name: grafana
    version: "7.0.11"
    repository: "https://grafana.github.io/helm-charts"
  - name: k8s-resources
    version: "1.0.1"
    repository: https://neuro-inc.github.io/helm-charts
