cloudProvider:
  type: gcp
  region: us-central1
  serviceAccountSecret:
    name: gcp-key
    key: key_json

platform:
  authUrl: https://dev.neu.ro
  configUrl: https://dev.neu.ro
  apiUrl: https://dev.neu.ro/api/v1
  accessTokenCookieName: dat
  clusterName: default
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: cluster_token

metricsApi:
  nameOverride: platform-metrics-api
  fullnameOverride: platform-metrics-api

  ingress:
    enabled: true
    ingressClassName: traefik
    hosts: [dev.neu.ro]

metricsExporter:
  nameOverride: platform-metrics-exporter
  fullnameOverride: platform-metrics-exporter

prometheusProxy:
  nameOverride: platform-prometheus-proxy
  fullnameOverride: platform-prometheus-proxy

grafanaProxy:
  nameOverride: platform-grafana-proxy
  fullnameOverride: platform-grafana-proxy

  ingress:
    enabled: true
    ingressClassName: traefik
    hosts: [grafana-dev.neu.ro, metrics-dev.neu.ro]
    annotations:
      traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
      traefik.ingress.kubernetes.io/router.middlewares: platform-platform-ingress-auth@kubernetescrd

secrets:
  - name: alertmanager-config
    data:
      alertmanager.yaml: |
        route:
          receiver: platform-notifications
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 4h
          group_by: [alertname]
          routes:
            - receiver: ignore
              matchers:
                - exported_service="default-backend@kubernetes"
              continue: false
            - receiver: ignore
              matchers:
                - exported_service=~"platform-jobs-.+"
              continue: false
            - receiver: ignore
              matchers:
                - namespace="platform-jobs"
              continue: false

        receivers:
          - name: ignore
          - name: platform-notifications
            webhook_configs:
              - url: http://platform-notifications:8080/api/v1/notifications/alert-manager-notification
                http_config:
                  authorization:
                    type: Bearer
                    credentials_file: /etc/alertmanager/secrets/platformservices-secret/compute_token

kube-prometheus-stack:
  kube-state-metrics:
    priorityClassName: "platform-services"

  prometheus:
    prometheusSpec:
      thanos:
        objectStorageConfig:
          existingSecret:
            name: thanos
            key: object-store.yaml

      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: standard-rwo

      externalLabels:
        cluster: default

      priorityClassName: "platform-services"

  alertmanager:
    alertmanagerSpec:
      configSecret: alertmanager-config

      secrets:
        - platformservices-secret

      priorityClassName: "platform-services"

  prometheusOperator:
    kubeletService:
      namespace: platform

    admissionWebhooks:
      patch:
        priorityClassName: "platform-services"

    priorityClassName: "platform-services"

  kubelet:
    namespace: platform

thanos:
  store:
    persistentVolumeClaim:
      spec:
        storageClassName: standard-rwo

  compact:
    persistentVolumeClaim:
      spec:
        storageClassName: standard-rwo

  objstoreSecretOverride: thanos
  priorityClassName: "platform-services"

grafana:
  adminPassword: password
  priorityClassName: "platform-services"

sentry:
  dsn: https://432bc48cd2444be7afec5efeb1fc03a6@o489136.ingest.sentry.io/5530426
  clusterName: dev
  sampleRate: 0.002

priorityClassName: "platform-services"
