cloudProvider:
  type: aws
  region: us-east-1

platform:
  authUrl: https://dev.neu.ro
  configUrl: https://dev.neu.ro
  apiUrl: https://dev.neu.ro/api/v1
  accessTokenCookieName: dat
  clusterName: default
  token:
    valueFrom:
      secretKeyRef:
        name: platformservices-secret
        key: cluster_token

metricsExporter:
  nameOverride: platform-metrics-exporter
  fullnameOverride: platform-metrics-exporter

  podMetadata:
    annotations:
      iam.amazonaws.com/role: arn:aws:iam::771188043543:role/pricing-366c09e4841fcc83df56b8f070c34716

prometheusProxy:
  nameOverride: platform-prometheus-proxy
  fullnameOverride: platform-prometheus-proxy

  replicas: 2

grafanaProxy:
  nameOverride: platform-grafana-proxy
  fullnameOverride: platform-grafana-proxy

  replicas: 2
  ingress:
    hosts: [metrics-dev.neu.ro]
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.middlewares: platform-ingress-auth@kubernetescrd
      external-dns.platform.neuromation.io: "true"
      # TODO: remove traefik v1 annotations
      ingress.kubernetes.io/auth-trust-headers: "true"
      ingress.kubernetes.io/auth-type: forward
      ingress.kubernetes.io/auth-url: https://dev.neu.ro/oauth/authorize
      traefik.frontend.rule.type: PathPrefix

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      thanos:
        objectStorageConfig:
          name: thanos-object-storage-config
          key: thanos-object-storage.yaml
      podMetadata:
        annotations:
          iam.amazonaws.com/role: arn:aws:iam::771188043543:role/s3-366c09e4841fcc83df56b8f070c34716
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp2

  prometheusOperator:
    kubeletService:
      namespace: platform

  kubelet:
    namespace: platform

thanos:
  store:
    persistentVolumeClaim:
      spec:
        storageClassName: gp2
    annotations:
      iam.amazonaws.com/role: arn:aws:iam::771188043543:role/s3-366c09e4841fcc83df56b8f070c34716

  bucket:
    annotations:
      iam.amazonaws.com/role: arn:aws:iam::771188043543:role/s3-366c09e4841fcc83df56b8f070c34716

  compact:
    persistentVolumeClaim:
      spec:
        storageClassName: gp2
    annotations:
      iam.amazonaws.com/role: arn:aws:iam::771188043543:role/s3-366c09e4841fcc83df56b8f070c34716

  objstore:
    type: S3
    config:
      bucket: neuro-dev-metrics
      endpoint: s3.us-east-1.amazonaws.com

grafana:
  adminPassword: password

sentry:
  dsn: https://432bc48cd2444be7afec5efeb1fc03a6@o489136.ingest.sentry.io/5530426
  clusterName: dev
  sampleRate: 0.002
