name: CI

on:
  push:
    branches: [master]
    tags: [v*.*, v*.*.*]
  pull_request:
    branches: [master]
  pull_request_target:
    branches: [master]
  schedule:
  - cron: 0 4 * * *

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    if: |
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]') ||
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]')
    env:
      CLOUD_PROVIDER: ${{ secrets.CLOUD_PROVIDER_DEV }}
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5
    - name: Cache packages
      uses: actions/cache@v2.1.6
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-py-3.8-${{ hashFiles('pyproject.toml', 'setup.cfg')
          }}
    - name: Install dependencies
      run: make setup
    - name: Lint
      run: |
        echo "::add-matcher::.github/actionlint-matcher.json"
        make lint
      env:
        CI_LINT_RUN: 1
    - name: Run unit tests
      run: make test_unit
    - name: Configure AWS credentials
      if: env.CLOUD_PROVIDER == 'aws'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Login to AWS ECR
      if: env.CLOUD_PROVIDER == 'aws'
      uses: aws-actions/amazon-ecr-login@v1
    - name: Configure Azure credentials
      if: env.CLOUD_PROVIDER == 'azure'
      uses: azure/login@v1.4.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Login to Azure ACR
      if: env.CLOUD_PROVIDER == 'azure'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_DEV_ACR_SERVER }}
        username: ${{ secrets.AZURE_DEV_ACR_USERNAME }}
        password: ${{ secrets.AZURE_DEV_ACR_PASSWORD }}
    - name: Start minikube
      run: |
        ./minikube.sh install
        ./minikube.sh start
    - name: Run integration tests
      run: make test_integration
    - name: Build image
      run: make docker_build
      working-directory: ${{ github.workspace }}
    - name: Upload image artifact
      uses: neuro-inc/upload-image-action@v21.9.2
      with:
        image: platform-reports
        token: ${{ secrets.GITHUB_TOKEN }}
  deploy_dev:
    name: Deploy on dev
    environment: dev
    runs-on: ubuntu-latest
    needs: test
    concurrency: deploy_dev
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AZURE_ACR_NAME: ${{ secrets.AZURE_DEV_ACR_NAME }}
      AZURE_REGION: ${{ secrets.AZURE_DEV_REGION }}
      AZURE_RG_NAME: ${{ secrets.AZURE_DEV_RG_NAME }}
      CLUSTER_NAME: ${{ secrets.DEV_CLUSTER_NAME }}
      HELM_ENV: dev
      CLOUD_PROVIDER: ${{ secrets.CLOUD_PROVIDER_DEV }}
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5
    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.7.0
    - name: Set image tag
      run: echo "IMAGE_TAG=$GITHUB_SHA" >> $GITHUB_ENV
    - name: Configure AWS credentials
      if: env.CLOUD_PROVIDER == 'aws'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Login to AWS ECR
      if: env.CLOUD_PROVIDER == 'aws'
      uses: aws-actions/amazon-ecr-login@v1
    - name: Configure Azure credentials
      if: env.CLOUD_PROVIDER == 'azure'
      uses: azure/login@v1.4.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Login to Azure ACR
      if: env.CLOUD_PROVIDER == 'azure'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_DEV_ACR_SERVER }}
        username: ${{ secrets.AZURE_DEV_ACR_USERNAME }}
        password: ${{ secrets.AZURE_DEV_ACR_PASSWORD }}
    - name: Push image to registry
      run: make docker_push
    - name: Update kube config
      run: make ${{ env.CLOUD_PROVIDER }}_k8s_login
    - name: Deploy to kubernetes
      run: make helm_deploy
